# Generated by Django 2.2.7 on 2019-12-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('comment', models.CharField(max_length=500)),
                ('datepost', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
