# Generated by Django 2.2.6 on 2020-02-01 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('danny', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comments',
        ),
    ]
