# Generated by Django 2.2.6 on 2019-12-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('titleID', models.TextField()),
                ('describe', models.TextField()),
                ('img', models.ImageField(blank=True, upload_to='photos')),
            ],
        ),
    ]
