# Generated by Django 2.2.6 on 2019-12-12 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='titleID',
        ),
    ]
