# Generated by Django 2.2.6 on 2019-12-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testimonies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('titleID', models.TextField()),
                ('testmony', models.TextField()),
                ('img', models.ImageField(blank=True, default='photos/defpic.jpg', upload_to='photos')),
                ('datepost', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
