# Generated by Django 2.2.6 on 2019-12-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmonials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonies',
            name='titleID',
            field=models.CharField(max_length=150),
        ),
    ]
